server:
    port: 41099
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1/pengeluaranku?useSSL=false&serverTimezone=Asia/Jakarta&verifyServerCertificate=false
        driver-class-name: com.mysql.jdbc.Driver
        username: pengeluaranku
        password: pengeluaranku
    jpa:
        database: MYSQL
        show-sql: false
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5Dialect

keycloak:
    realm : pengeluaranku
    auth-server-url : http://localhost:8080/auth
    ssl-required : external
    resource : api-pengeluaranku
    credentials:
        secret : 33748e4c-4fc2-4d07-b33b-b49f5ad650a2
    use-resource-role-mappings : true
    bearer-only: true

admin:
    keycloak:
        username: admin
        password: Demoneyesky0&1